development:
  adapter: postgresql
  database: buycoins_btc_api_dev_db
  # host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  # user: postgres
  # password: postgres
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  # database: buycoins_btc_api_test_db
  # host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  # username: postgres
  # password: postgres
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: buycoins_btc_api_prod_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
